#ifndef _ANIMATION_SPEEDS_H_
#define _ANIMATION_SPEEDS_H_

#define QUESTION_MARK_BLOCK_ANIMATION_SPEED 0.15f
#define BRICK_BLOCK_ANIMATION_SPEED 0.15f

#define KOOPA_WALK_ANIMATION_SPEED 0.15f
#define KOOPA_SHELL_ANIMATION_SPEED 0.08f

#define COIN_ANIMATION_SPEED 0.15f


#endif